service: pizza-to-dynamo
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  hello:
    handler: handler.create
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:683837296978:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status